name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  # Allows manual triggers from GitHub UI
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: git lfs install

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://kingno3l:$HF_TOKEN@huggingface.co/spaces/kingno3l/hybrid-xai-cdss-backend main
